### ISSUE TITLE
how to use your module in project?

### ISSUE THREAD

**Issue by devM4x** [IBM-Swift/HeliumLogger#20]
Hello developers. i realy can't found tutorials how to use (import in to project in xcode for example)your module or other modules from IBM Package Manager.  i try to use founded here https://swiftpkgs.ng.bluemix.net/package/IBM-Swift/HeliumLogger  in IBM Sandbox, but there only errors && crush :(. for example this link taken from IBM sandbox
https://swiftlang.ng.bluemix.net/#/repl?gitPackage=https:%2F%2Fgithub.com%2FIBM-Swift%2FHeliumLogger-Sample&swiftVersion=latest

Thanx for reply

**Comment by naithar** [comment]
The problem with HeliumLogger-Sample you are referencing is that it is not updated to current HeliumLogger version. It's referencing 0.9.x version instead of 0.16.x which is the current version.
You can make a fork and update the sample for any other repo you need. IMB Sandbox that faces  updated HeliumLogger-Sample does not crash.
https://swiftlang.ng.bluemix.net/#/repl?gitPackage=https:%2F%2Fgithub.com%2Fnaithar%2FHeliumLogger-Sample&swiftVersion=latest

**Comment by shmuelk** [comment]
HeliumLogger-Sample has been updated to use Swift 3.0 and LoggerAPI 1.0.
